#%RAML 1.0
policy_key: |
    {
      "type": "object",
      "$schema": "http://json-schema.org/draft-03/schema",
      "id": "http://jsonschema.net",
      "required": true,
      "properties": {
          "key-data": {
      "type": "object",
      "$schema": "http://json-schema.org/draft-03/schema",
      "id": "http://jsonschema.net",
      "required": true,
      "properties": {
        "account-id": {
          "type": "string",
          "required": true,
          "description": "Video Cloud account id"
        },
        "apis": {
          "type": "array",
          "required": false,
          "description": "Array of APIs that are permitted for this key (currently 'search' is the only one available - this must be included to to use the search funtionality for the Playback API)"
        },
        "allowed-domains": {
          "type": "array",
          "required": false,
          "description": "For domain restriction, the domains this key will work on"
        }
      }
      }
    }
