#%RAML 1.0
title: Policy API
description: Reference for the Brightcove Policy API, used to create policy keys to access the Playback API. Note that policy keys are generated automatically for Brightcove Players. This API is used to generate keys to access the Playback API __outside the context of a Brightcove Player__. To test API requests, you can use our [API Testing Tools](https://support.brightcove.com/concepts-testing-tools-brightcove-apis).
version: v1
baseUri: https://policy.api.brightcove.com/{version}
mediaType: application/json
types:
    account_id:
        type: string
        description: Video Cloud account id
    key_string:
        type: string
        description: The key string associated with a policy key
/accounts:
    /{account_id}:
        /policy_keys:
            post:
                description: Create a policy key
                body:
                    application/json:
                        type: object
                        example:
                            key-data:
                                account_id: 1752604059001
                                apis: ['search']
                                allowed-domains: ['support.brightcove.com', 'solutions.brightcove.com']
                            properties:
                                key-data:
                                    type: object
                                    required: true
                                    properties:
                                        account_id:
                                        apis:
                                            type: string[],
                                            required: false
                                            description: Array of APIs that are permitted for this key (currently 'search' is the only one available - this must be included to to use the search funtionality for the Playback API)
                                        allowed-domains:
                                            type: string[],
                                            required: false
                                            description: For domain restriction, the domains this key will work on
                responses:
                    200:
                        body:
                            application/json
                                example: |
                                {
                                    "key-string": "BCpkADawqM3Y8LpDbjIPcWKZSiCwNwbeAoZPIhFnkPq0LyyRpXfjmIYvPIr-x5G0G9MWx8INLb39GGbPgrOYQfv5yN-1xph02-AE2DAvU6sZ7KshLC5E9SqTFBPR-gDNd87Z7SLkbexUPgp78KYWjRuh2mxmV_mg3y_i5BMLQHLbvvLaRksV0j8khLx0pVgnkmsUy50cARhPM9rgC2n7pzGYGSbCBXAqDd6jssJp2f670OzSjbCMHS65yG8",
                                    "key-data": {
                                        "account-id": "1752604059001",
                                        "apis": [
                                            "search"
                                        ],
                                        "allowed-domains": [
                                            "http://support.brightcove.com",
                                            "https://solutions.brightcove.com"
                                        ]
                                    }
                                }
            /{key_string}:
                get:
                    description: Get a policy key
                urlParameters:
                    key_string:
                        description: the `key_string` from a policy key
                        type: string
                responses:
                    200:
                        body:
                            application/json
                                example: |
                                {
                                    "key-string": "BCpkADawqM3Y8LpDbjIPcWKZSiCwNwbeAoZPIhFnkPq0LyyRpXfjmIYvPIr-x5G0G9MWx8INLb39GGbPgrOYQfv5yN-1xph02-AE2DAvU6sZ7KshLC5E9SqTFBPR-gDNd87Z7SLkbexUPgp78KYWjRuh2mxmV_mg3y_i5BMLQHLbvvLaRksV0j8khLx0pVgnkmsUy50cARhPM9rgC2n7pzGYGSbCBXAqDd6jssJp2f670OzSjbCMHS65yG8",
                                    "key-data": {
                                        "account-id": "1752604059001",
                                        "apis": [
                                            "search"
                                        ],
                                        "allowed-domains": [
                                            "http://support.brightcove.com",
                                            "https://solutions.brightcove.com"
                                        ]
                                    }
                                }
securitySchemes:
  oauth_2_0:
      description: Most Brightcove APIs support OAuth 2.0 for authenticating API requests
      type: OAuth 2.0
      describedBy:
          headers:
              Authorization:
securedBy: [ oauth_2_0 ]
