#%RAML 1.0
title: Policy API
description: Reference for the Brightcove Policy API, used to create policy keys to access the Playback API. Note that policy keys are generated automatically for Brightcove Players. This API is used to generate keys to access the Playback API __outside the context of a Brightcove Player__. To test API requests, you can use our [API Testing Tools](https://support.brightcove.com/concepts-testing-tools-brightcove-apis).
version: v1
baseUri: https://policy.api.brightcove.com/{version}
mediaType: application/json
/accounts:
    /{account_id}:
        urlParameters:
            account_id:
                description: Video Cloud account id
                type: string
        /policy_keys:
            post:
                description: Create a policy key
                headers:
                    Content-Type: application/json
                    Authorization:
            /{key_string}:
                get:
                    description: Get a policy key
                urlParameters:
                    key_string:
                        description: the `key_string` from a policy key
                        type: string
securitySchemes:
  oauth_2_0: !include ../securitySchemes/oauth_2_0.raml
types:
  Policy Key:  !include types/policy_keys.raml
resourceTypes:
  collection: !include types/collection.raml
traits:
securedBy: [ oauth_2_0 ]
/search:
  /code:
    type: collection
    get:
